name = "nordyu-theme"
display-name = "dyu's Nord Theme"
description = "Nord-based color scheme."
icon = "icon.png"
version = "0.1.0"
author = "dyu"
repository = "https://github.com/dyu/nordyu-lapce"
color-themes = ["nord.toml"]
